# 使用 MySQL 官方镜像
#amd64
#FROM mysql:5.7
#arm64
FROM mysql
#容器端口映射3310
# 设置 MySQL root 用户密码
ENV MYSQL_ROOT_PASSWORD=123456789hh
ENV MYSQL_DATABASE=quick

# 将自定义的 my.cnf 复制到 MySQL 容器的配置目录中
COPY ./my.cnf /etc/mysql/conf.d/

# 初始化数据库脚本
COPY ./task.sql /docker-entrypoint-initdb.d/

# 暴露 MySQL 默认端口
EXPOSE 3306
