#Spring
spring:
  application:
    name: upc-gateway
  #在nacos注册中心注册服务,查找服务对应的ip和端口
  cloud:
    nacos:
      server-addr: 47.105.115.241:8848
    gateway:
      routes:
        - id: user-class-service
          uri: lb://user-class-service
          predicates:
            - Path=/userclass/**
          filters:
            - StripPrefix=1
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/project/**
          filters:
            - StripPrefix=1
        - id: exercise-service
          uri: lb://exercise-service
          predicates:
            - Path=/exercise/**
          filters:
            - StripPrefix=1
        - id: teachingprocess-resource-service
          uri: lb://teachingprocess-resource-service
          predicates:
            - Path=/process/**
          filters:
            - StripPrefix=1
        - id: knowledgebase-service
          uri: lb://knowledgebase-service
          predicates:
            - Path=/knowledge/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
#        cors-configurations:
#          '[/**]':
#            allowed-origin-patterns:
#              - "*"
#            allowed-methods:
#              - "*"
#            allowed-headers:
#              - "*"
#            allow-credentials: true
#            max-age: 3600






knife4j:
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    strategy: discover
    discover:
      enabled: true
      # 指定版本号(Swagger2|OpenAPI3)，springboot3只支持openapi3
      version : openapi3





#server
server:
  port: 8080

logging:
  level:
    upc.projectname: debug



