#Spring
spring:
  application:
    name: user-class-service
  cloud:
    nacos:
      server-addr: 47.105.115.241:8848
    #配置openfeign接口日志输出级别，与okhttp连接池子
    openfeign:
      client:
        config:
          default:
            logger-level: full
      okhttp:
        enabled: true
  #停止使用默认的用户名密码认证
  security:
    user:
      password: none


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ${mysql.password}

mysql:
  host: 118.190.217.72
  port: 3306
  database: ai-prepare
  password: 123456789hh!

#server
server:
  port: 8301

#日志级别,基本上每个微服务项目都要这个配置
logging:
  level:
    upc.projectname: debug

mybatis-plus:
  configuration:
    #配置mybatis-plus的日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #配置mybatis-plus的下划线转驼峰
    map-underscore-to-camel-case: true







#springdoc
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: upc.projectname #扫描组织名对应的包，这样的配置每个微服务都能用，因为组织名一样
#knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn